[package]
name = "neptune_intro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
injective-cosmwasm = "0.2.21"
injective-std = "0.1.5"
